process-engine/management_api_http

- .gitignore
- .npmignore
- ISSUE_TEMPLATE.md
- Jenkinsfile
- PULL_REQUEST_TEMPLATE.md
- README.md
- gulpfile.js
- ioc_module.js
- package.json
- src/endpoints/index.ts
- src/endpoints/process_model_execution/execution_controller.ts
- src/endpoints/process_model_execution/execution_router.ts
- src/endpoints/process_model_execution/index.ts
- src/index.ts
- src/middlewares/index.ts
- src/middlewares/resolve_management_context.ts
- tsconfig.json
- tslint.json
Depends on:
https://github.com/process-engine/management_api_contracts/pull/1
This PR marks the first feature in the ManagementAPI.
It is a duplicate behavior of the one implemented in the ConsumerAPI counterpart.
A main difference is the use of namespaces to dissect functional parts of the API from each other.
This PR is also meant to be the first example of how to use namespaces for such a scenario.
Currently there is no integration test setup for the ManagementAPI.
This will follow after a manual integrative test.
> Add "StartProcess" to process model execution namespace

- package.json
- src/endpoints/process_model_execution/execution_controller.ts
- src/endpoints/process_model_execution/execution_router.ts
Depends on:
* https://github.com/process-engine/management_api_contracts/pull/16
* renamed `updateProcessModelById` to `updateProcessDefinitionsByName` to reflect the change of entity
All integration tests in meta repositories should run successfully: 
* https://github.com/process-engine/management_api_meta/pull/6
* https://github.com/process-engine/consumer_api_meta/pull/40
* https://github.com/process-engine/deployment_api_meta/pull/3
* https://github.com/process-engine/process_engine_meta/pull/122
> Process definitions instead of process model

- PULL_REQUEST_TEMPLATE.md
- ioc_module.js
- package.json
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
- src/endpoints/heatmap/index.ts
- src/endpoints/index.ts
Adds and Endpoint and Controller for the Heatmap Feature.
Make request against the new endpoint.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br> …
> ✨ Feature/implement heatmap

- package.json
- src/endpoints/correlations/correlation_controller.ts
- src/endpoints/correlations/correlation_router.ts
Requires:
https://github.com/process-engine/management_api_contracts/pull/19
**Changes:**
1. Change all dependencies to fixed versions
2. Implement the `getProcessModelForCorrelation` endpoint
**Issues:**
Closes #12
PR: #13
Call the HTTP endpoint.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> ✨ Get process model for correlation

- package.json
- src/endpoints/correlations/correlation_controller.ts
- src/endpoints/correlations/correlation_router.ts
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
- src/endpoints/process_model_execution/execution_controller.ts
- src/endpoints/process_model_execution/execution_router.ts
**Changes:**
Add the following endpoints to the Correlation -router and -controller:
- `getAllCorrelations`: Gets all stored correlations
- `getActiveCorrelations`: gets all active correlations
- `getCorrelationById`: Gets a specific correlation by its ID
- `getCorrelationsByProcessModelId`: Gets all Correlations in which a specific ProcessModel was run
- `getCorrelationByProcessInstanceId`: Gets the Correlation in which a specific ProcessInstance was run
PR: #16
Make requests against the endpoints.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
> ✨ Inspect correlation features

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
**Changes:**
Add optional correlationId parameter to `getProcessModelLog` method to only return ProcessModelLogs for a specific correlation.
PR: #17
Use the Endpoint to request ProcessModelLogs for a specific Correlation.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
> ✨ Filter logs by correlation

- package.json
- src/endpoints/user_tasks/user_task_controller.ts
**Changes:**
Use Instance IDs for UserTask Events, instead of ModelIds.
This ensures that only one UserTask can ever be finished by a single request.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
PR: #18
Use the endpoint to make requests for finishing UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- Fixes Wrong …
> ♻️🔒 Use unique ids for UserTask events 

- package.json
- src/endpoints/process_model_execution/execution_controller.ts
- src/endpoints/process_model_execution/execution_router.ts
**Changes:**
1. Add delete process model functionality
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/64
PR: #20
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/141**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> ✨ Add Delete Process Model Functionality

- ioc_module.js
- package.json
- src/endpoints/correlations/correlation_controller.ts
- src/endpoints/events/event_controller.ts
- src/endpoints/events/event_router.ts
- src/endpoints/events/index.ts
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/index.ts
- src/endpoints/process_model_execution/execution_controller.ts
- src/endpoints/process_model_execution/execution_router.ts
- src/endpoints/user_tasks/user_task_controller.ts
**Changes:**
1. Implement the Event API endpoint.
2. Rename `getEventsForProcessModel` to `getStartEventsForProcessModel`
PR: #21
Use the Endpoint to make requests pertaining to the Event API.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code> …
> ✨ Implement event api

- package.json
- src/endpoints/process_model_execution/execution_socket_endpoint.ts
- src/endpoints/user_tasks/user_task_socket_endpoint.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #22
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> 🔒 Add Identity to Events

- ioc_module.js
- package.json
- src/endpoints/index.ts
- src/endpoints/manual_tasks/index.ts
- src/endpoints/manual_tasks/manual_task_controller.ts
- src/endpoints/manual_tasks/manual_task_router.ts
- src/endpoints/manual_tasks/manual_task_socket_endpoint.ts
**Changes:**
1. Add ManualTask Endpoints
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/91
PR: #19 
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
> ✨ Add ManualTask Endpoint

- package.json
- src/endpoints/process_model_execution/execution_socket_endpoint.ts
---
**Changes:**
1. This PR adds the socket endpoint for the ProcessInstanceStarted event.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #23
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
> ✨ Add endpoint for the ProcessInstanceStarted event

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
**Changes:**
1. Add function to get ActiveToken by Correlation and ProcessModel
2. Add function to get TokenHistory by Correlation and ProcessModel
PR: #24
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
> ✨ Add Function For LiveExecutionTracker

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
**Changes:**
1. Add type TokenHistoryGroup as return type for retrieving the TokenHistory for a ProcessModel in a Correlation.
PR: #25
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
> 💄 Use TokenHistoryGroup

- package.json
- src/endpoints/manual_tasks/manual_task_socket_endpoint.ts
- src/endpoints/process_model_execution/execution_socket_endpoint.ts
- src/endpoints/user_tasks/user_task_socket_endpoint.ts
**Changes:**
1. Upgrade `ManagementApiContracts` and apply the refactored EventAggregator messages.
2. Update all message paths used by the Socket.IO endpoint.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/198
PR: #28
These changes are internal. All should run as before.
> ✨ Get instances and tasks by identity 

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add getTokensForProcessInstance
2. Add getActiveTokensForProcessInstance
PR: #27 
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
> ✨ Add Get Token by Process Instance Functionality

- package.json
- src/endpoints/manual_tasks/manual_task_controller.ts
- src/endpoints/manual_tasks/manual_task_router.ts
- src/endpoints/process_models/process_model_controller.ts
- src/endpoints/process_models/process_model_router.ts
- src/endpoints/user_tasks/user_task_controller.ts
- src/endpoints/user_tasks/user_task_router.ts
> Related to process-engine/process_engine_runtime#207
**Changes:**
1. Add getProcessModelByProcessInstanceId
PR: #30
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR …
> ✨ Add getProcessModelByProcessInstanceId

- package.json
- src/endpoints/process_models/process_model_controller.ts
- src/endpoints/process_models/process_model_router.ts
**Changes:**
1. Add a new Route for terminating ProcessInstances.
2. Add `TerminateProcessInstance` Function to controller.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/199
PR: #35
> ✨Make Processes Interruptible

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/306
**Changes:**
1. Add Functions to Get Logs by ProcessInstanceId
PR: #38
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1448***
> ✨ Add Functions to Get Logs by ProcessInstanceId

- package.json
- src/endpoints/heatmap/heatmap_controller.ts
- src/endpoints/heatmap/heatmap_router.ts
**Changes:**
Rename the `getTokensForFlowNodeInstance` UseCase to `getTokensForFlowNode`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/311
PR: #39
This is only an internal refactoring, so the endpoint will work just like before.
> ♻️💄 Fix naming inconsistencies

- ioc_module.js
- package.json
- src/endpoints/boundary_event/boundary_event_socket_endpoint.ts
- src/endpoints/boundary_event/index.ts
- src/endpoints/call_activity/call_activity_socket_endpoint.ts
- src/endpoints/call_activity/index.ts
- src/endpoints/index.ts
- src/endpoints/intermediate_event/index.ts
- src/endpoints/intermediate_event/intermediate_event_socket_endpoint.ts
1. Add Events for Call Activities
2. Add Events for Boundary Events
3. Add Events for Intermediate Events
PR: #40
> Related to https://github.com/process-engine/process_engine_runtime/pull/334
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1412**
> ✨ Add Events for Call Activities, Boundary Events and Intermediate Events

- ioc_module.js
- package.json
- src/endpoints/flow_node_instances/flow_node_instance_controller.ts
- src/endpoints/flow_node_instances/flow_node_instance_router.ts
- src/endpoints/flow_node_instances/index.ts
- src/endpoints/index.ts
1. Add endpoint for getFlowNodeInstancesForProcessInstance
Closes #YourIssueNumber
PR: #41
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> ✨ Add endpoint for getFlowNodeInstancesForProcessInstance

- ioc_module.js
- package-lock.json
- package.json
- src/endpoints/cronjobs/cronjob_controller.ts
- src/endpoints/cronjobs/cronjob_router.ts
- src/endpoints/cronjobs/index.ts
- src/endpoints/index.ts
1. Add `cronjobs` endpoint with `getAllActiveCronjobs` route registration
Part of https://github.com/process-engine/process_engine_runtime/issues/363
PR: #45
- Deploy some ProcessModels with cyclic `TimerStartEvents`
- Start the CronjobService
- Access the `getAllActiveCronjobs` route and see that a list with all cronjobs is returned
> ✨Add getActiveCronjobs UseCase

- package-lock.json
- package.json
- src/endpoints/cronjobs/cronjob_controller.ts
- src/endpoints/cronjobs/cronjob_router.ts
Add endpoints for retrieving a cronjob history.
Part of https://github.com/process-engine/process_engine_runtime/issues/365
PR: #46
> ✨Persist cronjob history

- package.json
- src/endpoints/correlation/correlation_controller.ts
- src/endpoints/cronjob/cronjob_controller.ts
- src/endpoints/empty_activity/empty_activity_controller.ts
- src/endpoints/event/event_controller.ts
- src/endpoints/flow_node_instance/flow_node_instance_controller.ts
- src/endpoints/kpi/kpi_controller.ts
- src/endpoints/logging/logging_controller.ts
- src/endpoints/manual_task/manual_task_controller.ts
- src/endpoints/process_model/process_model_controller.ts
- src/endpoints/token_history/token_history_controller.ts
- src/endpoints/user_task/user_task_controller.ts
Add `offset` and `limit` to each query that returns a list of values.
Part of https://github.com/process-engine/process_engine_runtime/issues/379
PR: #37
> ✨ Add limit and offset to list queries

- ioc_module.js
- package.json
- src/endpoints/cronjob/cronjob_socket_endpoint.ts
- src/endpoints/cronjob/index.ts
- src/endpoints/empty_activity/empty_activity_socket_endpoint.ts
- src/endpoints/manual_task/manual_task_socket_endpoint.ts
- src/endpoints/process_model/process_model_socket_endpoint.ts
1. Add cronjob socket endpoint
PR: #48 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
> ✨Add conjob socket endpoint

- src/middlewares/resolve_identity.ts
Add a check to the `resolveIdentity` middleware, which will verify a request's Auth-header.
If the header contains multiple tokens, an error is thrown, since this is not supported.
Part of https://github.com/process-engine/process_engine_runtime/issues/396
PR: #51
Make requests against the endpoint, which contain authorization headers with multiple tokens and see what happens.
> 🔒 Throw error, if an Authorization header contains multiple tokens

- .gitignore
- Jenkinsfile
- ioc_module.js
- package.json
- src/endpoints/index.ts
- src/endpoints/process_model/process_model_router.ts
- src/endpoints/swagger/index.ts
- src/endpoints/swagger/swagger_controller.ts
- src/endpoints/swagger/swagger_router.ts
- src/middlewares/resolve_identity.ts
- swagger-generator/swagger-generator.ts
- swagger-generator/tsconfig.json
1. Add Swagger Generator
PR: #54
> ✨ Add Swagger Generator
